number_word_in_lessons: 20
number_answers: 4
activity:
  follow: "follow"
  unfollow: "unfollow"
  learned: "learned"
  learning: "learning"
option:
  - all_word
  - learned
  - no_learn
follow_type:
  - following
  - followers
gravatar_size: 50
gravatar_size_large: 60
lessons:
  success: "Lessons have create"
activities:
  followed: followed
  unfollowed: unfollowed
  learned: learned
  a_lesson_in: have had a lesson in
  learning: is learning
  cant: has not enough words to start the lesson
paginate_per_page: 10
time: time_ago_in_words
page_per: 15
lesson:
  duration_in_minutes: 2
